;;; References:
;; Awesome Emacs
;;   https://github.com/emacs-tw/awesome-emacs
;; GNU ELPA
;;   https://elpa.gnu.org
;; GNU Emacs
;;   https://www.gnu.org/software/emacs/manual/html_node/emacs/Custom-Themes.html
;;   https://www.gnu.org/software/emacs/manual/html_node/emacs/Creating-Custom-Themes.html
;;   https://www.gnu.org/software/emacs/manual/html_node/emacs/Faces.html
;;   https://www.gnu.org/software/emacs/manual/html_node/emacs/Standard-Faces.html
;;   https://www.gnu.org/software/emacs/manual/html_node/emacs/Face-Customization.html
;;   https://www.gnu.org/software/emacs/manual/html_node/elisp/Face-Attributes.html
;;   https://www.gnu.org/software/emacs/manual/html_node/elisp/Faces-for-Font-Lock.html
;;   https://www.gnu.org/software/emacs/manual/html_node/elisp/Display-Feature-Testing.html
;; marmalade repo
;;   https://marmalade-repo.org
;; MELPA
;;   https://melpa.org
;;   https://stable.melpa.org

;;; Code:

(unless (>= emacs-major-version 24)
  (error "Totus theme requires Emacs 24 or later!"))

(deftheme totus "")

(defgroup totus nil
  "Totus theme customizations.
  The theme has to be reloaded after changing anything in this group."
  :group 'faces)

(defcustom totus-region-highlight nil
  "Allows to set a region highlight style based on the Totus components.
Valid styles are
- 'snowstorm' - Uses 'totus0' as foreground- and 'totus4' as background color
- 'frost' - Uses 'totus0' as foreground- and 'totus8' as background color"
  :type 'string
  :group 'totus)

(defcustom totus-uniform-mode-lines nil
  "Enables uniform activate- and inactive mode lines using 'totus3' as background."
  :type 'boolean
  :group 'totus)

(setq totus-theme--brightened-comments '("#4c566a" "#4e586d" "#505b70" "#525d73" "#556076" "#576279" "#59647c" "#5b677f" "#5d6982" "#5f6c85" "#616e88" "#63718b" "#66738e" "#687591" "#6a7894" "#6d7a96" "#6f7d98" "#72809a" "#75829c" "#78859e" "#7b88a1"))

(defun totus-display-truecolor-or-graphic-p ()
  "Returns whether the display can display totus colors"
  (or (= (display-color-cells) 16777216) (display-graphic-p)))

;;;; Color Constants
(let ((class '((class color) (min-colors 89)))
      (totus0 (if (totus-display-truecolor-or-graphic-p) "#ffffff" nil))
      (totus1 (if (totus-display-truecolor-or-graphic-p) "#f3f1f3" "black"))
      (totus2 (if (totus-display-truecolor-or-graphic-p) "#f3f1f3" "#f3f1f3"))
      (totus3 (if (totus-display-truecolor-or-graphic-p) "#f3f1f3" "brightblack"))
      (totus4 (if (totus-display-truecolor-or-graphic-p) "#4a484d" "#4a484d"))
      (totus5 (if (totus-display-truecolor-or-graphic-p) "#5f4d4f" "white"))
      (totus6 (if (totus-display-truecolor-or-graphic-p) "#4a484d" "brightwhite"))
      (totus7 (if (totus-display-truecolor-or-graphic-p) "#185870" "cyan"))
      (totus8 (if (totus-display-truecolor-or-graphic-p) "#005589" "brightcyan"))
      (totus9 (if (totus-display-truecolor-or-graphic-p) "#1d3fcf" "blue"))
      (totus10 (if (totus-display-truecolor-or-graphic-p) "#2d48b0" "brightblue"))
      (totus11 (if (totus-display-truecolor-or-graphic-p) "#a80000" "red"))
      (totus12 (if (totus-display-truecolor-or-graphic-p) "#4a5700" "brightyellow"))
      (totus13 (if (totus-display-truecolor-or-graphic-p) "#714900" "yellow"))
      (totus14 (if (totus-display-truecolor-or-graphic-p) "#005f26" "green"))
      (totus15 (if (totus-display-truecolor-or-graphic-p) "#882a7a" "magenta"))
      (totus-annotation (if (totus-display-truecolor-or-graphic-p) "#4a5700" "brightyellow"))
      (totus-attribute (if (totus-display-truecolor-or-graphic-p) "#185870" "cyan"))
      (totus-class (if (totus-display-truecolor-or-graphic-p) "#185870" "cyan"))
      (totus-comment (if (totus-display-truecolor-or-graphic-p) "#5f4d4f" "brightblack"))
      (totus-escape (if (totus-display-truecolor-or-graphic-p) "#4a5700" "brightyellow"))
      (totus-method (if (totus-display-truecolor-or-graphic-p) "#005589" "brightcyan"))
      (totus-keyword (if (totus-display-truecolor-or-graphic-p) "#1d3fc8" "blue"))
      (totus-numeric (if (totus-display-truecolor-or-graphic-p) "#882a7a" "magenta"))
      (totus-operator (if (totus-display-truecolor-or-graphic-p) "#1d3fcf" "blue"))
      (totus-preprocessor (if (totus-display-truecolor-or-graphic-p) "#2d48b0" "brightblue"))
      (totus-punctuation (if (totus-display-truecolor-or-graphic-p) "#4a484d" "#D8DEE9"))
      (totus-regexp (if (totus-display-truecolor-or-graphic-p) "#714900" "yellow"))
      (totus-string (if (totus-display-truecolor-or-graphic-p) "#005f26" "green"))
      (totus-tag (if (totus-display-truecolor-or-graphic-p) "#1d3fcf" "blue"))
      (totus-variable (if (totus-display-truecolor-or-graphic-p) "#4a484d" "#D8DEE9"))
      (totus-region-highlight-foreground (if (totus-display-truecolor-or-graphic-p) "#ffffff" nil))
      (totus-region-highlight-background (if (totus-display-truecolor-or-graphic-p) "#4a484d" nil))
      (totus-uniform-mode-lines-background (if totus-uniform-mode-lines "#f3f1f3" "#ffffff")))

;;;; +------------+
;;;; + Core Faces +
;;;; +------------+
  (custom-theme-set-faces
   'totus
   `(calendar-weekend-header ((,class (:foreground ,totus11))))
   `(change-log-acknowledgment ((,class (:foreground ,totus10))))
   `(compilation-column-number ((,class (:foreground ,totus4))))
   `(dired-ignored ((,class (:foreground ,totus4))))
   `(dired-perm-write ((,class (:foreground ,totus4))))
   `(fill-column-indicator ((,class (:foreground ,totus4))))
   `(line-number ((,class (:foreground ,totus4))))
   `(line-number-current-line ((,class (:foreground ,totus9))))
   `(log-edit-unknown-header ((,class (:foreground ,totus11))))

   ;; +--- Base ---+
   `(bold ((,class (:weight bold))))
   `(bold-italic ((,class (:weight bold :slant italic))))
   `(default ((,class (:foreground ,totus4 :background ,totus0))))
   `(error ((,class (:foreground ,totus11 :weight bold))))
   `(escape-glyph ((,class (:foreground ,totus12))))
   `(font-lock-builtin-face ((,class (:foreground ,totus9))))
   `(font-lock-comment-face ((,class (:foreground ,totus-comment))))
   `(font-lock-comment-delimiter-face ((,class (:foreground ,totus-comment))))
   `(font-lock-constant-face ((,class (:foreground ,totus9))))
   `(font-lock-doc-face ((,class (:foreground ,totus-comment))))
   `(font-lock-function-name-face ((,class (:foreground ,totus8))))
   `(font-lock-keyword-face ((,class (:foreground ,totus9))))
   `(font-lock-negation-char-face ((,class (:foreground ,totus9))))
   `(font-lock-preprocessor-face ((,class (:foreground ,totus10 :weight bold))))
   `(font-lock-reference-face ((,class (:foreground ,totus9))))
   `(font-lock-regexp-grouping-backslash ((,class (:foreground ,totus13))))
   `(font-lock-regexp-grouping-construct ((,class (:foreground ,totus13))))
   `(font-lock-string-face ((,class (:foreground ,totus14))))
   `(font-lock-type-face ((,class (:foreground ,totus7))))
   `(font-lock-variable-name-face ((,class (:foreground ,totus4))))
   `(font-lock-warning-face ((,class (:foreground ,totus13))))
   `(italic ((,class (:slant italic))))
   `(shadow ((,class (:foreground ,totus3))))
   `(underline ((,class (:underline t))))
   `(warning ((,class (:foreground ,totus13 :weight bold))))

   ;; +--- Syntax ---+
   ;; > C
   `(c-annotation-face ((,class (:foreground ,totus-annotation))))

   ;; > diff
   `(diff-added ((,class (:foreground ,totus14))))
   `(diff-changed ((,class (:foreground ,totus13))))
   `(diff-context ((,class (:inherit default))))
   `(diff-file-header ((,class (:foreground ,totus8))))
   `(diff-function ((,class (:foreground ,totus7))))
   `(diff-header ((,class (:foreground ,totus9 :weight bold))))
   `(diff-hunk-header ((,class (:foreground ,totus9 :background ,totus0))))
   `(diff-indicator-added ((,class (:foreground ,totus14))))
   `(diff-indicator-changed ((,class (:foreground ,totus13))))
   `(diff-indicator-removed ((,class (:foreground ,totus11))))
   `(diff-nonexistent ((,class (:foreground ,totus11))))
   `(diff-refine-added ((,class (:foreground ,totus14))))
   `(diff-refine-changed ((,class (:foreground ,totus13))))
   `(diff-refine-removed ((,class (:foreground ,totus11))))
   `(diff-removed ((,class (:foreground ,totus11))))

   ;; +--- UI ---+
   `(border ((,class (:foreground ,totus4))))
   `(buffer-menu-buffer ((,class (:foreground ,totus4 :weight bold))))
   `(button ((,class (:background ,totus0 :foreground ,totus8 :box (:line-width 2 :color ,totus4 :style sunken-button)))))
   `(completions-annotations ((,class (:foreground ,totus9))))
   `(completions-common-part ((,class (:foreground ,totus8 :weight bold))))
   `(completions-first-difference ((,class (:foreground ,totus11))))
   `(custom-button ((,class (:background ,totus0 :foreground ,totus8 :box (:line-width 2 :color ,totus4 :style sunken-button)))))
   `(custom-button-mouse ((,class (:background ,totus4 :foreground ,totus0 :box (:line-width 2 :color ,totus4 :style sunken-button)))))
   `(custom-button-pressed ((,class (:background ,totus6 :foreground ,totus0 :box (:line-width 2 :color ,totus4 :style sunken-button)))))
   `(custom-button-pressed-unraised ((,class (:background ,totus4 :foreground ,totus0 :box (:line-width 2 :color ,totus4 :style sunken-button)))))
   `(custom-button-unraised ((,class (:background ,totus0 :foreground ,totus8 :box (:line-width 2 :color ,totus4 :style sunken-button)))))
   `(custom-changed ((,class (:foreground ,totus13))))
   `(custom-comment ((,class (:foreground ,totus-comment))))
   `(custom-comment-tag ((,class (:foreground ,totus7))))
   `(custom-documentation ((,class (:foreground ,totus4))))
   `(custom-group-tag ((,class (:foreground ,totus8 :weight bold))))
   `(custom-group-tag-1 ((,class (:foreground ,totus8 :weight bold))))
   `(custom-invalid ((,class (:foreground ,totus11))))
   `(custom-modified ((,class (:foreground ,totus13))))
   `(custom-rogue ((,class (:foreground ,totus12 :background ,totus2))))
   `(custom-saved ((,class (:foreground ,totus14))))
   `(custom-set ((,class (:foreground ,totus8))))
   `(custom-state ((,class (:foreground ,totus14))))
   `(custom-themed ((,class (:foreground ,totus8 :background ,totus2))))
   `(cursor ((,class (:background ,totus4 :foreground ,totus0))))
   `(fringe ((,class (:foreground ,totus4 :background ,totus0))))
   `(file-name-shadow ((,class (:inherit shadow :foreground ,totus4))))
   `(header-line ((,class (:foreground ,totus4 :background ,totus2))))
   `(help-argument-name ((,class (:foreground ,totus8))))
   `(highlight ((,class (:foreground ,totus8 :background ,totus2))))
   `(hl-line ((,class (:background ,totus1))))
   `(info-menu-star ((,class (:foreground ,totus9))))
   `(isearch ((,class (:foreground ,totus0 :background ,totus8))))
   `(isearch-fail ((,class (:foreground ,totus11))))
   `(link ((,class (:underline t))))
   `(link-visited ((,class (:underline t))))
   `(linum ((,class (:foreground ,totus3 :background ,totus0))))
   `(linum-relative-current-face ((,class (:foreground ,totus3 :background ,totus0))))
   `(match ((,class (:inherit isearch))))
   `(message-cited-text ((,class (:foreground ,totus4))))
   `(message-header-cc ((,class (:foreground ,totus9))))
   `(message-header-name ((,class (:foreground ,totus7))))
   `(message-header-newsgroup ((,class (:foreground ,totus14))))
   `(message-header-other ((,class (:foreground ,totus4))))
   `(message-header-subject ((,class (:foreground ,totus8))))
   `(message-header-to ((,class (:foreground ,totus9))))
   `(message-header-xheader ((,class (:foreground ,totus13))))
   `(message-mml ((,class (:foreground ,totus10))))
   `(message-separator ((,class (:inherit shadow :foreground ,totus4))))
   `(minibuffer-prompt ((,class (:foreground ,totus8 :weight bold))))
   `(mm-command-output ((,class (:foreground ,totus8))))
   `(mode-line ((,class (:foreground ,totus8 :background ,totus3))))
   `(mode-line-buffer-id ((,class (:weight bold))))
   `(mode-line-highlight ((,class (:inherit highlight))))
   `(mode-line-inactive ((,class (:foreground ,totus4 :background ,totus-uniform-mode-lines-background))))
   `(next-error ((,class (:inherit error))))
   `(nobreak-space ((,class (:foreground ,totus3 :background ,totus4))))
   `(outline-1 ((,class (:foreground ,totus8 :weight bold))))
   `(outline-2 ((,class (:inherit outline-1))))
   `(outline-3 ((,class (:inherit outline-1))))
   `(outline-4 ((,class (:inherit outline-1))))
   `(outline-5 ((,class (:inherit outline-1))))
   `(outline-6 ((,class (:inherit outline-1))))
   `(outline-7 ((,class (:inherit outline-1))))
   `(outline-8 ((,class (:inherit outline-1))))
   `(package-description ((,class (:foreground ,totus4))))
   `(package-help-section-name ((,class (:foreground ,totus8 :weight bold))))
   `(package-name ((,class (:foreground ,totus8))))
   `(package-status-available ((,class (:foreground ,totus7))))
   `(package-status-avail-obso ((,class (:foreground ,totus7 :slant italic))))
   `(package-status-built-in ((,class (:foreground ,totus9))))
   `(package-status-dependency ((,class (:foreground ,totus8 :slant italic))))
   `(package-status-disabled ((,class (:foreground ,totus3))))
   `(package-status-external ((,class (:foreground ,totus12 :slant italic))))
   `(package-status-held ((,class (:foreground ,totus4 :weight bold))))
   `(package-status-new ((,class (:foreground ,totus14))))
   `(package-status-incompat ((,class (:foreground ,totus11))))
   `(package-status-installed ((,class (:foreground ,totus7 :weight bold))))
   `(package-status-unsigned ((,class (:underline ,totus13))))
   `(query-replace ((,class (:foreground ,totus8 :background ,totus2))))
   `(region ((,class (:foreground ,totus-region-highlight-foreground :background ,totus-region-highlight-background))))
   `(scroll-bar ((,class (:background ,totus3))))
   `(secondary-selection ((,class (:background ,totus2))))

   ;; `show-paren-match-face` and `show-paren-mismatch-face` are deprecated since Emacs version 22.1 and were
   ;; removed in Emacs 25.
   ;; https://github.com/arcticicestudio/totus-emacs/issues/75
   ;; http://git.savannah.gnu.org/cgit/emacs.git/commit/?id=c430f7e23fc2c22f251ace4254e37dea1452dfc3
   ;; https://github.com/emacs-mirror/emacs/commit/c430f7e23fc2c22f251ace4254e37dea1452dfc3
   `(show-paren-match-face ((,class (:foreground ,totus0 :background ,totus8))))
   `(show-paren-mismatch-face ((,class (:background ,totus11))))

   `(show-paren-match ((,class (:foreground ,totus0 :background ,totus8))))
   `(show-paren-mismatch ((,class (:background ,totus11))))
   `(success ((,class (:foreground ,totus14))))
   `(term ((,class (:foreground ,totus4 :background ,totus0))))
   `(term-color-black ((,class (:foreground ,totus1 :background ,totus1))))
   `(term-color-white ((,class (:foreground ,totus5 :background ,totus5))))
   `(term-color-cyan ((,class (:foreground ,totus7 :background ,totus7))))
   `(term-color-blue ((,class (:foreground ,totus8 :background ,totus8))))
   `(term-color-red ((,class (:foreground ,totus11 :background ,totus11))))
   `(term-color-yellow ((,class (:foreground ,totus13 :background ,totus13))))
   `(term-color-green ((,class (:foreground ,totus14 :background ,totus14))))
   `(term-color-magenta ((,class (:foreground ,totus15 :background ,totus15))))
   `(tool-bar ((,class (:foreground ,totus4 :background ,totus3))))
   `(tooltip ((,class (:foreground ,totus0 :background ,totus4))))
   `(trailing-whitespace ((,class (:foreground ,totus3))))
   `(tty-menu-disabled-face ((,class (:foreground ,totus1))))
   `(tty-menu-enabled-face ((,class (:background ,totus2 foreground ,totus4))))
   `(tty-menu-selected-face ((,class (:foreground ,totus8 :underline t))))
   `(undo-tree-visualizer-current-face ((,class (:foreground ,totus8))))
   `(undo-tree-visualizer-default-face ((,class (:foreground ,totus4))))
   `(undo-tree-visualizer-unmodified-face ((,class (:foreground ,totus4))))
   `(undo-tree-visualizer-register-face ((,class (:foreground ,totus9))))
   `(vc-conflict-state ((,class (:foreground ,totus12))))
   `(vc-edited-state ((,class (:foreground ,totus13))))
   `(vc-locally-added-state ((,class (:underline ,totus14))))
   `(vc-locked-state ((,class (:foreground ,totus10))))
   `(vc-missing-state ((,class (:foreground ,totus11))))
   `(vc-needs-update-state ((,class (:foreground ,totus12))))
   `(vc-removed-state ((,class (:foreground ,totus11))))
   `(vc-state-base ((,class (:foreground ,totus4))))
   `(vc-up-to-date-state ((,class (:foreground ,totus8))))
   `(vertical-border ((,class (:foreground ,totus2))))
   `(which-func ((,class (:foreground ,totus8))))
   `(whitespace-big-indent ((,class (:foreground ,totus3 :background ,totus0))))
   `(whitespace-empty ((,class (:foreground ,totus3 :background ,totus0))))
   `(whitespace-hspace ((,class (:foreground ,totus3 :background ,totus0))))
   `(whitespace-indentation ((,class (:foreground ,totus3 :background ,totus0))))
   `(whitespace-line ((,class (:background ,totus0))))
   `(whitespace-newline ((,class (:foreground ,totus3 :background ,totus0))))
   `(whitespace-space ((,class (:foreground ,totus3 :background ,totus0))))
   `(whitespace-space-after-tab ((,class (:foreground ,totus3 :background ,totus0))))
   `(whitespace-space-before-tab ((,class (:foreground ,totus3 :background ,totus0))))
   `(whitespace-tab ((,class (:foreground ,totus3 :background ,totus0))))
   `(whitespace-trailing ((,class (:inherit trailing-whitespace))))
   `(widget-button-pressed ((,class (:foreground ,totus9 :background ,totus1))))
   `(widget-documentation ((,class (:foreground ,totus4))))
   `(widget-field ((,class (:background ,totus2 :foreground ,totus4))))
   `(widget-single-line-field ((,class (:background ,totus2 :foreground ,totus4))))
   `(window-divider ((,class (:background ,totus3))))
   `(window-divider-first-pixel ((,class (:background ,totus3))))
   `(window-divider-last-pixel ((,class (:background ,totus3))))

    ;;;; +-----------------+
    ;;;; + Package Support +
    ;;;; +-----------------+
   ;; +--- Syntax ---+
   ;; > Auctex
   `(font-latex-bold-face ((,class (:inherit bold))))
   `(font-latex-italic-face ((,class (:inherit italic))))
   `(font-latex-math-face ((,class (:foreground ,totus8))))
   `(font-latex-sectioning-0-face ((,class (:foreground ,totus8 :weight bold))))
   `(font-latex-sectioning-1-face ((,class (:inherit font-latex-sectioning-0-face))))
   `(font-latex-sectioning-2-face ((,class (:inherit font-latex-sectioning-0-face))))
   `(font-latex-sectioning-3-face ((,class (:inherit font-latex-sectioning-0-face))))
   `(font-latex-sectioning-4-face ((,class (:inherit font-latex-sectioning-0-face))))
   `(font-latex-sectioning-5-face ((,class (:inherit font-latex-sectioning-0-face))))
   `(font-latex-script-char-face ((,class (:inherit font-lock-warning-face))))
   `(font-latex-string-face ((,class (:inherit font-lock-string-face))))
   `(font-latex-warning-face ((,class (:inherit font-lock-warning-face))))

   ;; > Elixir
   `(elixir-attribute-face ((,class (:foreground ,totus-annotation))))
   `(elixir-atom-face ((,class (:foreground ,totus4 :weight bold))))

   ;; > Enhanced Ruby
   `(enh-ruby-heredoc-delimiter-face ((,class (:foreground ,totus14))))
   `(enh-ruby-op-face ((,class (:foreground ,totus9))))
   `(enh-ruby-regexp-delimiter-face ((,class (:foreground ,totus13))))
   `(enh-ruby-regexp-face ((,class (:foreground ,totus13))))
   `(enh-ruby-string-delimiter-face ((,class (:foreground ,totus14))))
   `(erm-syn-errline ((,class (:foreground ,totus11 :underline t))))
   `(erm-syn-warnline ((,class (:foreground ,totus13 :underline t))))

   ;; > Java Development Environment for Emacs
   `(jdee-db-active-breakpoint-face ((,class (:background ,totus2 :weight bold))))
   `(jdee-bug-breakpoint-cursor ((,class (:background ,totus2))))
   `(jdee-db-requested-breakpoint-face ((,class (:foreground ,totus13 :background ,totus2 :weight bold))))
   `(jdee-db-spec-breakpoint-face ((,class (:foreground ,totus14 :background ,totus2 :weight bold))))
   `(jdee-font-lock-api-face ((,class (:foreground ,totus4))))
   `(jdee-font-lock-code-face ((,class (:slant italic))))
   `(jdee-font-lock-constant-face ((,class (:foreground ,totus-keyword))))
   `(jdee-font-lock-constructor-face ((,class (:foreground ,totus-method))))
   `(jdee-font-lock-doc-tag-face ((,class (:foreground ,totus7))))
   `(jdee-font-lock-link-face ((,class (:underline t))))
   `(jdee-font-lock-modifier-face ((,class (:foreground ,totus-keyword))))
   `(jdee-font-lock-number-face ((,class (:foreground ,totus-numeric))))
   `(jdee-font-lock-operator-fac ((,class (:foreground ,totus-operator))))
   `(jdee-font-lock-package-face ((,class (:foreground ,totus-class))))
   `(jdee-font-lock-pre-face ((,class (:foreground ,totus-comment :slant italic))))
   `(jdee-font-lock-private-face ((,class (:foreground ,totus-keyword))))
   `(jdee-font-lock-public-face ((,class (:foreground ,totus-keyword))))
   `(jdee-font-lock-variable-face ((,class (:foreground ,totus-variable))))

   ;; > JavaScript 2
   `(js2-function-call ((,class (:foreground ,totus8))))
   `(js2-private-function-call ((,class (:foreground ,totus8))))
   `(js2-jsdoc-html-tag-delimiter ((,class (:foreground ,totus6))))
   `(js2-jsdoc-html-tag-name ((,class (:foreground ,totus9))))
   `(js2-external-variable ((,class (:foreground ,totus4))))
   `(js2-function-param ((,class (:foreground ,totus4))))
   `(js2-jsdoc-value ((,class (:foreground ,totus-comment))))
   `(js2-jsdoc-tag ((,class (:foreground ,totus7))))
   `(js2-jsdoc-type ((,class (:foreground ,totus7))))
   `(js2-private-member ((,class (:foreground ,totus4))))
   `(js2-object-property ((,class (:foreground ,totus4))))
   `(js2-error ((,class (:foreground ,totus11))))
   `(js2-warning ((,class (:foreground ,totus13))))
   `(js2-instance-member ((,class (:foreground ,totus4))))

   ;; > JavaScript 3
   `(js3-error-face ((,class (:foreground ,totus11))))
   `(js3-external-variable-face ((,class (:foreground ,totus4))))
   `(js3-function-param-face ((,class (:foreground ,totus4))))
   `(js3-instance-member-face ((,class (:foreground ,totus4))))
   `(js3-jsdoc-html-tag-delimiter-face ((,class (:foreground ,totus6))))
   `(js3-jsdoc-html-tag-name-face ((,class (:foreground ,totus9))))
   `(js3-jsdoc-tag-face ((,class (:foreground ,totus9))))
   `(js3-jsdoc-type-face ((,class (:foreground ,totus7))))
   `(js3-jsdoc-value-face ((,class (:foreground ,totus4))))
   `(js3-magic-paren-face ((,class (:inherit show-paren-match-face))))
   `(js3-private-function-call-face ((,class (:foreground ,totus8))))
   `(js3-private-member-face ((,class (:foreground ,totus4))))
   `(js3-warning-face ((,class (:foreground ,totus13))))

   ;; > Markdown
   `(markdown-blockquote-face ((,class (:foreground ,totus-comment))))
   `(markdown-bold-face ((,class (:inherit bold))))
   `(markdown-header-face-1 ((,class (:foreground ,totus8))))
   `(markdown-header-face-2 ((,class (:foreground ,totus8))))
   `(markdown-header-face-3 ((,class (:foreground ,totus8))))
   `(markdown-header-face-4 ((,class (:foreground ,totus8))))
   `(markdown-header-face-5 ((,class (:foreground ,totus8))))
   `(markdown-header-face-6 ((,class (:foreground ,totus8))))
   `(markdown-inline-code-face ((,class (:foreground ,totus7))))
   `(markdown-italic-face ((,class (:inherit italic))))
   `(markdown-link-face ((,class (:foreground ,totus8))))
   `(markdown-markup-face ((,class (:foreground ,totus9))))
   `(markdown-reference-face ((,class (:inherit markdown-link-face))))
   `(markdown-url-face ((,class (:foreground ,totus4 :underline t))))

   ;; > Rainbow Delimeters
   `(rainbow-delimiters-depth-1-face ((,class :foreground ,totus7)))
   `(rainbow-delimiters-depth-2-face ((,class :foreground ,totus8)))
   `(rainbow-delimiters-depth-3-face ((,class :foreground ,totus9)))
   `(rainbow-delimiters-depth-4-face ((,class :foreground ,totus10)))
   `(rainbow-delimiters-depth-5-face ((,class :foreground ,totus12)))
   `(rainbow-delimiters-depth-6-face ((,class :foreground ,totus13)))
   `(rainbow-delimiters-depth-7-face ((,class :foreground ,totus14)))
   `(rainbow-delimiters-depth-8-face ((,class :foreground ,totus15)))
   `(rainbow-delimiters-unmatched-face ((,class :foreground ,totus11)))

   ;; > Web Mode
   `(web-mode-attr-tag-custom-face ((,class (:foreground ,totus-attribute))))
   `(web-mode-builtin-face ((,class (:foreground ,totus-keyword))))
   `(web-mode-comment-face ((,class (:foreground ,totus-comment))))
   `(web-mode-comment-keyword-face ((,class (:foreground ,totus-comment))))
   `(web-mode-constant-face ((,class (:foreground ,totus-variable))))
   `(web-mode-css-at-rule-face ((,class (:foreground ,totus-annotation))))
   `(web-mode-css-function-face ((,class (:foreground ,totus-method))))
   `(web-mode-css-property-name-face ((,class (:foreground ,totus-keyword))))
   `(web-mode-css-pseudo-class-face ((,class (:foreground ,totus-class))))
   `(web-mode-css-selector-face ((,class (:foreground ,totus-keyword))))
   `(web-mode-css-string-face ((,class (:foreground ,totus-string))))
   `(web-mode-doctype-face ((,class (:foreground ,totus-preprocessor))))
   `(web-mode-function-call-face ((,class (:foreground ,totus-method))))
   `(web-mode-function-name-face ((,class (:foreground ,totus-method))))
   `(web-mode-html-attr-name-face ((,class (:foreground ,totus-attribute))))
   `(web-mode-html-attr-equal-face ((,class (:foreground ,totus-punctuation))))
   `(web-mode-html-attr-value-face ((,class (:foreground ,totus-string))))
   `(web-mode-html-entity-face ((,class (:foreground ,totus-keyword))))
   `(web-mode-html-tag-bracket-face ((,class (:foreground ,totus-punctuation))))
   `(web-mode-html-tag-custom-face ((,class (:foreground ,totus-tag))))
   `(web-mode-html-tag-face ((,class (:foreground ,totus-tag))))
   `(web-mode-html-tag-namespaced-face ((,class (:foreground ,totus-keyword))))
   `(web-mode-json-key-face ((,class (:foreground ,totus-class))))
   `(web-mode-json-string-face ((,class (:foreground ,totus-string))))
   `(web-mode-keyword-face ((,class (:foreground ,totus-keyword))))
   `(web-mode-preprocessor-face ((,class (:foreground ,totus-preprocessor))))
   `(web-mode-string-face ((,class (:foreground ,totus-string))))
   `(web-mode-symbol-face ((,class (:foreground ,totus-variable))))
   `(web-mode-type-face ((,class (:foreground ,totus-class))))
   `(web-mode-warning-face ((,class (:inherit ,font-lock-warning-face))))
   `(web-mode-variable-name-face ((,class (:foreground ,totus-variable))))

   ;; +--- UI ---+
   ;; > Anzu
   `(anzu-mode-line ((,class (:foreground, totus8))))
   `(anzu-mode-line-no-match ((,class (:foreground, totus11))))

   ;; > Avy
   `(avy-lead-face ((,class (:background ,totus11 :foreground ,totus5))))
   `(avy-lead-face-0 ((,class (:background ,totus10 :foreground ,totus5))))
   `(avy-lead-face-1 ((,class (:background ,totus3 :foreground ,totus5))))
   `(avy-lead-face-2 ((,class (:background ,totus15 :foreground ,totus5))))

   ;; > Company
   `(company-echo-common ((,class (:foreground ,totus0 :background ,totus4))))
   `(company-preview ((,class (:foreground ,totus0 :background ,totus10))))
   `(company-preview-common ((,class (:foreground ,totus0 :background ,totus8))))
   `(company-preview-search ((,class (:foreground ,totus0 :background ,totus8))))
   `(company-scrollbar-bg ((,class (:foreground ,totus1 :background ,totus1))))
   `(company-scrollbar-fg ((,class (:foreground ,totus2 :background ,totus2))))
   `(company-template-field ((,class (:foreground ,totus0 :background ,totus7))))
   `(company-tooltip ((,class (:foreground ,totus4 :background ,totus2))))
   `(company-tooltip-annotation ((,class (:foreground ,totus12))))
   `(company-tooltip-annotation-selection ((,class (:foreground ,totus12 :weight bold))))
   `(company-tooltip-common ((,class (:foreground ,totus8))))
   `(company-tooltip-common-selection ((,class (:foreground ,totus8 :background ,totus3))))
   `(company-tooltip-mouse ((,class (:inherit highlight))))
   `(company-tooltip-selection ((,class (:background ,totus3 :weight bold))))

   ;; > diff-hl
   `(diff-hl-change ((,class (:background ,totus13 :foreground ,totus0))))
   `(diff-hl-insert ((,class (:background ,totus14 :foreground ,totus0))))
   `(diff-hl-delete ((,class (:background ,totus11 :foreground ,totus0))))

   ;; > Evil
   `(evil-ex-info ((,class (:foreground ,totus8))))
   `(evil-ex-substitute-replacement ((,class (:foreground ,totus9))))
   `(evil-ex-substitute-matches ((,class (:inherit isearch))))

   ;; > Flycheck
   `(flycheck-error ((,class (:underline (:style wave :color ,totus11)))))
   `(flycheck-fringe-error ((,class (:foreground ,totus11 :weight bold))))
   `(flycheck-fringe-info ((,class (:foreground ,totus8 :weight bold))))
   `(flycheck-fringe-warning ((,class (:foreground ,totus13 :weight bold))))
   `(flycheck-info ((,class (:underline (:style wave :color ,totus8)))))
   `(flycheck-warning ((,class (:underline (:style wave :color ,totus13)))))

   ;; > Git Gutter
   `(git-gutter:modified ((,class (:foreground ,totus13))))
   `(git-gutter:added ((,class (:foreground ,totus14))))
   `(git-gutter:deleted ((,class (:foreground ,totus11))))

   ;; > Git Gutter Plus
   `(git-gutter+-modified ((,class (:foreground ,totus13))))
   `(git-gutter+-added ((,class (:foreground ,totus14))))
   `(git-gutter+-deleted ((,class (:foreground ,totus11))))

   ;; > Helm
   `(helm-bookmark-addressbook ((,class (:foreground ,totus7))))
   `(helm-bookmark-directory ((,class (:foreground ,totus9))))
   `(helm-bookmark-file ((,class (:foreground ,totus8))))
   `(helm-bookmark-gnus ((,class (:foreground ,totus10))))
   `(helm-bookmark-info ((,class (:foreground ,totus14))))
   `(helm-bookmark-man ((,class (:foreground ,totus4))))
   `(helm-bookmark-w3m ((,class (:foreground ,totus9))))
   `(helm-buffer-directory ((,class (:foreground ,totus9))))
   `(helm-buffer-file ((,class (:foreground ,totus8))))
   `(helm-buffer-not-saved ((,class (:foreground ,totus13))))
   `(helm-buffer-process ((,class (:foreground ,totus10))))
   `(helm-buffer-modified ((,class (:foreground ,totus10))))
   `(helm-candidate-number ((,class (:foreground ,totus4 :weight bold))))
   `(helm-candidate-number-suspended ((,class (:foreground ,totus4))))
   `(helm-delete-async-message ((,class (:foreground ,totus11))))
   `(helm-ff-directory ((,class (:foreground ,totus9 :weight bold))))
   `(helm-ff-dirs ((,class (:foreground ,totus9))))
   `(helm-ff-dotted-directory ((,class (:foreground ,totus10 :underline t))))
   `(helm-ff-dotted-symlink-director ((,class (:foreground ,totus7 :weight bold))))
   `(helm-ff-executable ((,class (:foreground ,totus8))))
   `(helm-ff-file ((,class (:foreground ,totus4))))
   `(helm-ff-invalid-symlink ((,class (:foreground ,totus11 :weight bold))))
   `(helm-ff-prefix ((,class (:foreground ,totus0 :background ,totus9))))
   `(helm-ff-symlink ((,class (:foreground ,totus7))))
   `(helm-grep-cmd-line ((,class (:foreground ,totus4 :background ,totus0))))
   `(helm-grep-file ((,class (:foreground ,totus8))))
   `(helm-grep-finish ((,class (:foreground ,totus5))))
   `(helm-grep-lineno ((,class (:foreground ,totus4))))
   `(helm-grep-match ((,class (:inherit isearch))))
   `(helm-grep-running ((,class (:foreground ,totus8))))
   `(helm-header ((,class (:foreground ,totus9 :background ,totus2))))
   `(helm-header-line-left-margin ((,class (:foreground ,totus9 :background ,totus2))))
   `(helm-history-deleted ((,class (:foreground ,totus11))))
   `(helm-history-remote ((,class (:foreground ,totus4))))
   `(helm-lisp-completion-info ((,class (:foreground ,totus4 :weight bold))))
   `(helm-lisp-show-completion ((,class (:inherit isearch))))
   `(helm-locate-finish ((,class (:foreground ,totus14))))
   `(helm-match ((,class (:foreground ,totus8))))
   `(helm-match-item ((,class (:inherit isearch))))
   `(helm-moccur-buffer ((,class (:foreground ,totus8))))
   `(helm-resume-need-update ((,class (:foreground ,totus0 :background ,totus13))))
   `(helm-selection ((,class (:inherit highlight :foreground ,totus2 :background ,totus4))))
   `(helm-selection-line ((,class (:background ,totus2))))
   `(helm-source-header ((,class (:height 1.44 :foreground ,totus8 :background ,totus2))))
   `(helm-swoop-line-number-face ((,class (:foreground ,totus4 :background ,totus0))))
   `(helm-swoop-target-word-face ((,class (:foreground ,totus0 :background ,totus7))))
   `(helm-swoop-target-line-face ((,class (:background ,totus13 :foreground ,totus3))))
   `(helm-swoop-target-line-block-face ((,class (:background ,totus13 :foreground ,totus3))))
   `(helm-separator ((,class (:background ,totus2))))
   `(helm-visible-mark ((,class (:background ,totus4 :foreground ,totus1))))

   ;; > Magit
   `(magit-branch ((,class (:foreground ,totus7 :weight bold))))
   `(magit-cherry-unmatched ((,class (:foreground ,totus10))))
   `(magit-diff-context-highlight ((,class (:background ,totus2))))
   `(magit-diff-file-header ((,class (:foreground ,totus8 :box (:color ,totus8)))))
   `(magit-diff-whitespace-warning ((,class (:foreground ,totus4))))
   `(magit-diffstat-added ((,class (:foreground ,totus14))))
   `(magit-diffstat-removed ((,class (:foreground ,totus11))))
   `(magit-hash ((,class (:foreground ,totus8))))
   `(magit-hunk-heading ((,class (:foreground ,totus9))))
   `(magit-hunk-heading-highlight ((,class (:foreground ,totus9 :background ,totus2))))
   `(magit-item-highlight ((,class (:foreground ,totus8 :background ,totus2))))
   `(magit-log-author ((,class (:foreground ,totus7))))
   `(magit-process-ng ((,class (:foreground ,totus13 :weight bold))))
   `(magit-process-ok ((,class (:foreground ,totus14 :weight bold))))
   `(magit-reflog-cherry-pick ((,class (:foreground ,totus14))))
   `(magit-reflog-cherry-pick ((,class (:foreground ,totus14))))
   `(magit-reflog-commit ((,class (:foreground ,totus14))))
   `(magit-reflog-merge ((,class (:foreground ,totus14))))
   `(magit-reflog-other ((,class (:foreground ,totus10))))
   `(magit-reflog-remote ((,class (:foreground ,totus10))))
   `(magit-section-heading ((,class (:foreground ,totus7 :weight bold))))
   `(magit-section-highlight ((,class (:background ,totus2))))
   `(magit-signature-untrusted ((,class (:foreground ,totus10))))

   ;; > MU4E
   `(mu4e-header-marks-face ((,class (:foreground ,totus9))))
   `(mu4e-title-face ((,class (:foreground ,totus8))))
   `(mu4e-header-key-face ((,class (:foreground ,totus8))))
   `(mu4e-highlight-face ((,class (:highlight))))
   `(mu4e-flagged-face ((,class (:foreground ,totus13))))
   `(mu4e-unread-face ((,class (:foreground ,totus13 :weight bold))))
   `(mu4e-link-face ((,class (:underline t))))

   ;; > Powerline
   `(powerline-active1 ((,class (:foreground ,totus4 :background ,totus1))))
   `(powerline-active2 ((,class (:foreground ,totus4 :background ,totus3))))
   `(powerline-inactive1 ((,class (:background ,totus2))))
   `(powerline-inactive2 ((,class (:background ,totus2))))

   ;; > Powerline Evil
   `(powerline-evil-base-face ((,class (:foreground ,totus4))))
   `(powerline-evil-normal-face ((,class (:background ,totus8))))
   `(powerline-evil-insert-face ((,class (:foreground ,totus0 :background ,totus4))))
   `(powerline-evil-visual-face ((,class (:foreground ,totus0 :background ,totus7))))
   `(powerline-evil-replace-face ((,class (:foreground ,totus0 :background ,totus9))))

   ;; > NeoTree
   `(neo-banner-face ((,class (:foreground ,totus10))))
   `(neo-dir-link-face ((,class (:foreground ,totus9))))
   `(neo-expand-btn-face ((,class (:foreground ,totus6 :bold t))))
   `(neo-file-link-face ((,class (:foreground ,totus4))))
   `(neo-root-dir-face ((,class (:foreground ,totus7 :weight bold))))
   `(neo-vc-added-face ((,class (:foreground ,totus14))))
   `(neo-vc-conflict-face ((,class (:foreground ,totus11))))
   `(neo-vc-default-face ((,class (:foreground ,totus4))))
   `(neo-vc-edited-face ((,class (:foreground ,totus13))))
   `(neo-vc-ignored-face ((,class (:foreground ,totus3))))
   `(neo-vc-missing-face ((,class (:foreground ,totus12))))
   `(neo-vc-needs-merge-face ((,class (:background ,totus12 :foreground ,totus4))))
   `(neo-vc-needs-update-face ((,class (:background ,totus10 :foreground ,totus4))))
   `(neo-vc-removed-face ((,class (:foreground ,totus11 :strike-through nil))))
   `(neo-vc-up-to-date-face ((,class (:foreground ,totus4))))
   `(neo-vc-user-face ((,class (:foreground ,totus4))))

   ;; > Cider
   `(cider-result-overlay-face ((t (:background unspecified))))

   ;; > Org
   `(org-level-1 ((,class (:foreground ,totus7 :weight extra-bold))))
   `(org-level-2 ((,class (:foreground ,totus8 :weight bold))))
   `(org-level-3 ((,class (:foreground ,totus9 :weight semi-bold))))
   `(org-level-4 ((,class (:foreground ,totus10 :weight normal))))
   `(org-level-5 ((,class (:inherit org-level-4))))
   `(org-level-6 ((,class (:inherit org-level-4))))
   `(org-level-7 ((,class (:inherit org-level-4))))
   `(org-level-8 ((,class (:inherit org-level-4))))
   `(org-agenda-structure ((,class (:foreground ,totus9))))
   `(org-agenda-date ((,class (:foreground ,totus8 :underline nil))))
   `(org-agenda-done ((,class (:foreground ,totus14))))
   `(org-agenda-dimmed-todo-face ((,class (:foreground ,totus4))))
   `(org-archived ((,class (:background ,totus12 :foreground ,totus1))))
   `(org-block ((,class (:foreground ,totus4))))
   `(org-block-background ((,class (:background ,totus0))))
   `(org-block-begin-line ((,class (:foreground ,totus7))))
   `(org-block-end-line ((,class (:foreground ,totus7))))
   `(org-checkbox ((,class (:foreground ,totus9))))
   `(org-checkbox-statistics-done ((,class (:foreground ,totus14))))
   `(org-checkbox-statistics-todo ((,class (:foreground ,totus13))))
   `(org-code ((,class (:foreground ,totus7))))
   `(org-column ((,class (:background ,totus2))))
   `(org-column-title ((,class (:inherit org-column :weight bold :underline t))))
   `(org-date ((,class (:foreground ,totus8))))
   `(org-document-info ((,class (:foreground ,totus4))))
   `(org-document-info-keyword ((,class (:foreground ,totus4))))
   `(org-document-title ((,class (:foreground ,totus8 :weight bold))))
   `(org-done ((,class (:foreground ,totus14 :weight bold))))
   `(org-ellipsis ((,class (:foreground ,totus3 :background ,totus4))))
   `(org-footnote ((,class (:foreground ,totus8))))
   `(org-formula ((,class (:foreground ,totus9))))
   `(org-hide ((,class (:foreground ,totus0 :background ,totus1))))
   `(org-link ((,class (:underline t))))
   `(org-meta-line ((,class (:foreground ,totus4))))
   `(org-scheduled ((,class (:foreground ,totus14))))
   `(org-scheduled-previously ((,class (:foreground ,totus13))))
   `(org-scheduled-today ((,class (:foreground ,totus8))))
   `(org-special-keyword ((,class (:foreground ,totus9))))
   `(org-table ((,class (:foreground ,totus9))))
   `(org-todo ((,class (:foreground ,totus13 :weight bold))))
   `(org-upcoming-deadline ((,class (:foreground ,totus12))))
   `(org-warning ((,class (:foreground ,totus13 :weight bold))))
   `(font-latex-bold-face ((,class (:inherit bold))))
   `(font-latex-italic-face ((,class (:slant italic))))
   `(font-latex-string-face ((,class (:foreground ,totus14))))
   `(font-latex-match-reference-keywords ((,class (:foreground ,totus9))))
   `(font-latex-match-variable-keywords ((,class (:foreground ,totus4))))
   `(ido-only-match ((,class (:foreground ,totus8))))
   `(org-sexp-date ((,class (:foreground ,totus7))))
   `(ido-first-match ((,class (:foreground ,totus8 :weight bold))))
   `(ido-subdir ((,class (:foreground ,totus9))))
   `(org-quote ((,class (:inherit org-block :slant italic))))
   `(org-verse ((,class (:inherit org-block :slant italic))))
   `(org-agenda-date-weekend ((,class (:foreground ,totus9))))
   `(org-agenda-date-today ((,class (:foreground ,totus8 :weight bold))))
   `(org-agenda-done ((,class (:foreground ,totus14))))
   `(org-verbatim ((,class (:foreground ,totus7))))

   ;; > ivy-mode
   `(ivy-current-match ((,class (:inherit region))))
   `(ivy-minibuffer-match-face-1 ((,class (:inherit default))))
   `(ivy-minibuffer-match-face-2 ((,class (:background ,totus7 :foreground ,totus0))))
   `(ivy-minibuffer-match-face-3 ((,class (:background ,totus8 :foreground ,totus0))))
   `(ivy-minibuffer-match-face-4 ((,class (:background ,totus9 :foreground ,totus0))))
   `(ivy-remote ((,class (:foreground ,totus14))))
   `(ivy-posframe ((,class (:background ,totus1))))
   `(ivy-posframe-border ((,class (:background ,totus1))))
   `(ivy-remote ((,class (:foreground ,totus14))))

   ;; > perspective
   `(persp-selected-face ((,class (:foreground ,totus8 :weight bold))))))

;;;###autoload
(when (and (boundp 'custom-theme-load-path) load-file-name)
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'totus)

;; Local Variables:
;; no-byte-compile: t
;; indent-tabs-mode: nil
;; End:

;;; totus-theme.el ends here
